---
title: "vectors and data frames"
author: "Azul Carrillo"
date: "2022-10-20"
output: html_document
---


# The relationship between vectors and data frames 
## How to create Vectors 
```{r}
a_number <- 100 
length(a_number)
c(1,2,3)
c(FALSE,TRUE, TRUE)
c("Luna","Jai","Azul","Marcos")
1:4
0.5:5
c(1,6,7,100, -1)
1:100
long_vector <- 1:546378 # column opperator so you dont have to type every number 
length(long_vector)
tail(long_vector)
seq(1,100,0.3)# 1- 100 in increments of 0.3
seq(-100,5,2)
100:20
-100:5 # start. end 
rep(1:5, 3) # 1- 5 REPEATERD 3 times 
rep("luna",100)
rep(c(TRUE, FALSE, TRUE),7)
letters
LETTERS
```
# Joining vectors to create data frames 
```{r}
year_data <- data.frame(names = c("Azul", "Jai", "Marcos"),
                        year = c(4,3,4),
                        college = "UC Merced")
```


```{r}
yew_taxus <- data.frame(length = c(2.2, 2.1, 2.7, 3.0, 3.1, 2.5, 1.9, 1.1, 3.5, 2.9),
           width = c(1.3, 2.2, 1.5, 4.5, 3.1, NA, 1.8, 0.5, 2.0, 2.7),
           height = c(9.6, 7.6, 2.2, 1.5, 4.0, 3.0, 4.5, 2.3, 7.5, 3.2), 
           genus = "Taxus", 
           species = "baccata" )

```
## Extracting values from vectors and data frames 

```{r}
surveys <- read.csv("../raw-data/surveys.csv")
```

```{r}
#extracting one column at a time $ 
surveys$year
surveys$month
surveys$species_id
# if we want to extract rows and or multiple columns we use square brakets 
surveys[1,2]
surveys[1:5, ] # rows 1-5 all columns 
surveys[10:5, ]
surveys[10:5, "month" ]

surveys[10:5, c("month", "year")]
#use a single square bracket will keeep the data frame structure 
surveys["month"] # remains as a dat frame 
surveys[,"month"]# as a vector 
surveys[["month"]]
```


```{r}
surveys_weight <- surveys$weigh
surveys_month <- surveys[,"month"]
surveys_hindfoot <- surveys$hindfoot_leangth 
mean(surveys_hindfoot, is.rm = TRUE)  
```


```{r}
letters[1:5]
letters[c(17,12,9,3)]
letters[5:1]
letters[-1]
letters[-c(1,6,8,9)]
colnames(surveys)
surveys[,-(1:4)] #eliminate colums 1- 4 
```


```{r}

```







